.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LEIF" "1" "August 2013" "" ""
.
.SH "NAME"
\fBleif\fR \- A hypermedia browser for the CloudApp Collection+JSON API\.
.
.SH "SYNOPSIS"
\fBleif\fR
.
.SH "DESCRIPTION"
\fBleif\fR is a program to explore the CloudApp hypermedia API\. It was built so developers could feel how the API flows to help them consume it in their programs\.
.
.SH "INTERACTIVE COMMANDS"
.
.TP
\fBroot\fR
Go back to the root\.
.
.TP
\fBfollow\fR \fIrel\fR
Follow link with the relation \fIrel\fR on the collection or selected item\.
.
.TP
\fBcreate\fR
Begin editing the template to create a new item\.
.
.TP
\fBupdate\fR
Begin editing the template to update the item selected with \fBitems\fR\.
.
.TP
\fBrequest\fR
Reprint the details of the last request\.
.
.TP
\fBresponse\fR
Reprint the details of the last response\.
.
.TP
\fBtemplate\fR
Print the template from the last response\.
.
.TP
\fBitems\fR
Print each item from the last response one at a time in order to update, delete, or follow an item\'s link\.
.
.TP
\fBitem\fR
Print the selected item\.
.
.TP
\fBbasic\fR [\fIusername\fR [\fIpassword\fR]]
Authenticate with HTTP Basic and reload the current resource\. Will be prompted for username and password if omitted\.
.
.TP
\fBtoken\fR \fItoken\fR
Authenticate using the given token and reload the current resource\.
.
.TP
\fBdebug\fR
Print debug output from the previous HTTP request and response\.
.
.TP
\fBhelp\fR
Print available commands\.
.
.TP
\fBquit\fR
Exit \fBleif\fR\.
.
.SH "EXAMPLES"
Follow a rel=account link:
.
.IP "" 4
.
.nf

> follow account
.
.fi
.
.IP "" 0
.
.P
Use HTTP Basic authentication and reload the current resource:
.
.IP "" 4
.
.nf

> basic
Username: arthur@dent\.com
Password: ********
.
.fi
.
.IP "" 0
.
.P
Set token authentication:
.
.IP "" 4
.
.nf

> token abc123def456
.
.fi
.
.IP "" 0
.
.P
Create a new item filling the \fBname\fR and \fBbookmark_url\fR fields:
.
.IP "" 4
.
.nf

> create

Name (empty to submit): name
Value: CloudApp

Name (empty to submit): bookmark_url
Value: http://getcloudapp\.com

Name (empty to submit):
.
.fi
.
.IP "" 0
.
.P
Update an item filling the \fBpassword\fR field:
.
.IP "" 4
.
.nf

> update

Select this item to update [y,n]? y

Name (empty to submit): password
Value: towel

Name (empty to submit):
.
.fi
.
.IP "" 0
.
.P
JSON primitives (null, integers, and booleans) are interpreted as such\. Use quotes for literal strings\.
.
.IP "" 4
.
.nf

> create

Name (empty to submit): private
Value: true

Name (empty to submit): name
Value: "true"
.
.fi
.
.IP "" 0

